parameters:
#    m3e_hello.example.class: M3e\HelloBundle\Example

services:
#    m3e_hello.example:
#        class: %m3e_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
